// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Ohajiki",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Ohajiki",
            targets: ["AppModule"],
            bundleIdentifier: "app.natsukawa.natsu.Ohajiki",
            teamIdentifier: "F57NV9A334",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("onboarding.mp4")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)